### ISSUE TITLE
There is no usable Makefile

### ISSUE THREAD

**Issue by ceremcem** [vi/virtual_touchscreen#1]
This makefile consists of only one line, it's not usable.

**Comment by vi** [comment]
You are supposed to start building of the kernel module from Linux kernel's directory:

```
~/src/git/linux2$ make modules M=/home/vi/code/virtual_touchscreen/
  CC [M]  /home/vi/code/virtual_touchscreen/virtual_touchscreen.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/vi/code/virtual_touchscreen/virtual_touchscreen.mod.o
  LD [M]  /home/vi/code/virtual_touchscreen/virtual_touchscreen.ko
```

If you still have problems, ask.

**Comment by ceremcem** [comment]
Oh, sorry about that. Now I'm trying that way.

**Comment by vi** [comment]
I've just verified that virtual_touchscreen.ko works on my current kernel v4.1.2.

**Comment by ceremcem** [comment]
This may take some time since I need to make a cross compile (it's a bit tricky for me).
I'm closing this issue since it's a RTFM problem.
